### ISSUE TITLE
Code Audit

### ISSUE THREAD

**Issue by fohristiwhirl** [fohristiwhirl/nibbler#34]
In which we read through the codebase.

- [x] function XY(s)
- [x] function S(x, y)
- [x] function InfoVal(s, key)
- [x] function InfoPV(s)
- [x] function CompareArrays(a, b)
- [x] function ArrayStartsWith(a, b)
- [x] function ArrayIncludes(a, b)
- [x] function OppositeColour(s)
- [x] function ReplaceAll(s, search, replace)
- [x] function SafeString(s)
- [x] function Log(s)
- [x] function New2DArray(width, height)
- [x] function CanvasCoords(x, y)
- [x] function Point(a, b)
- [x] const position_prototype
- [ ] move: function(s)
- [ ] illegal: function(s)
- [x] sequence_illegal: function(moves)
- [x] los: function(x1, y1, x2, y2)
- [x] attacked: function(target, my_colour)
- [x] line_attack: function(target, step_x, step_y, my_colour)
- [x] find: function(piece, startx, starty, endx, endy)
- [x] parse_pgn: function(s)
- [x] piece: function(point)
- [x] is_white: function(point)
- [x] is_black: function(point)
- [x] is_empty: function(point)
- [x] colour: function(point)
- [x] same_colour: function(point1, point2)
- [ ] nice_string: function(s)
- [x] next_number_string: function()
- [x] fen: function()
- [x] copy: function()
- [x] function NewPosition(state = null, active = "w", castling = "", enpassant = null, halfmove = 0, fullmove = 1)
- [x] function LoadFEN(fen)
- [x] const node_prototype
- [x] make_move: function(s, force_new_node)
- [x] history: function()
- [x] future_history: function()
- [x] get_root: function()
- [x] get_end: function()
- [x] get_board: function()
- [x] promote_to_main_line: function()
- [x] fen: function()
- [x] nice_move: function()
- [x] token: function()
- [x] detach: function()
- [x] function NewNode(parent, move)
- [x] function NewTree(startpos)
- [x] function DestroyTree(node)
- [x] function __destroy_tree(node)
- [x] function split_buffer(buf)
- [x] function new_byte_pusher(size)
- [x] function new_pgn_record()
- [x] function PreParsePGN(buf)
- [x] function LoadPGNRecord(o)
- [x] function SavePGN(filename, node)
- [x] function PGNToClipboard(node)
- [x] function make_movetext(node)
- [x] function TokenNodeConnections(node)
- [x] function new_string_node_connector()
- [x] function write_tree(node, connector, skip_self_flag, force_number_string)
- [x] function get_movelist_highlight()
- [x] function fix_scrollbar_position(node)
- [x] function NewMovelistHander()
- [x] handler.draw = function(node)
- [x] handler.draw_lazy = function(node)
- [x] handler.draw_hard = function(node)
- [x] handler.redraw_node = function(node)
- [x] handler.node_from_click = function(event)
- [x] function NewInfoHandler()
- [x] ih.clear = function()
- [x] ih.err_receive = function(s)
- [x] ih.receive = function(s, board)
- [x] ih.sorted = function()
- [x] ih.must_draw_infobox = function()
- [x] ih.draw_infobox = function(mouse_point, active_square, leela_should_go, active_colour, searchmoves)
- [x] ih.moves_from_click = function(event)
- [x] ih.searchmove_from_click = function(event)
- [x] ih.draw_arrows = function()
- [x] const info_prototype
- [x] nice_pv: function()
- [x] value: function()
- [x] value_string: function(dp, force_0_100_scale)
- [x] function new_info(board, move)
- [x] function NewEngine()
- [x] eng.send = function(msg)
- [x] eng.setoption = function(name, value)
- [x] eng.sync = function()
- [x] eng.setup = function(engine_path, args, receive_fn, err_receive_fn, log_info_lines)
- [x] function NewRenderer()
- [x] renderer.position_changed = function(new_game_flag)
- [x] renderer.set_versus = function(s)
- [x] renderer.move = function(s)
- [x] renderer.play_info_index = function(n)
- [x] renderer.prev = function()
- [x] renderer.next = function()
- [x] renderer.goto_root = function()
- [x] renderer.goto_end = function()
- [x] renderer.return_to_main_line = function()
- [x] renderer.promote_to_main_line = function()
- [x] renderer.delete_move = function()
- [x] renderer.load_fen = function(s)
- [x] renderer.new_game = function()
- [x] renderer.pgn_to_clipboard = function()
- [x] renderer.save = function(filename)
- [x] renderer.open = function(filename)
- [x] renderer.load_pgn_from_string = function(s)
- [x] renderer.load_pgn_buffer = function(buf)
- [x] renderer.load_pgn_object = function(o)
- [x] renderer.show_pgn_chooser = function()
- [x] renderer.hide_pgn_chooser = function()
- [x] renderer.pgnchooser_click = function(event)
- [x] renderer.validate_pgn = function(filename)
- [x] renderer.leela_should_go = function()
- [x] renderer.receive = function(s)
- [x] renderer.err_receive = function(s)
- [x] renderer.go_or_halt = function(new_game_flag)
- [x] renderer.__halt = function()
- [x] renderer.__go = function(new_game_flag)
- [x] renderer.validate_searchmoves = function()
- [x] renderer.reset_leela_cache = function()
- [x] renderer.switch_weights = function(filename)
- [x] renderer.toggle_flip = function()
- [x] renderer.escape = function()
- [x] renderer.toggle_debug_css = function()
- [x] renderer.set_active_square = function(new_point)
- [x] renderer.mouse_point = function()
- [x] renderer.boardfriends_click = function(event)
- [x] renderer.infobox_click = function(event)
- [x] renderer.maybe_searchmove_click = function(event)
- [x] renderer.movelist_click = function(event)
- [x] renderer.show_promotiontable = function(partial_move)
- [x] renderer.hide_promotiontable = function()
- [x] renderer.handle_drop = function(event)
- [x] renderer.console = function(...args)
- [x] renderer.toggle = function(option)
- [x] renderer.draw_friendlies_in_table = function()
- [x] renderer.draw_enemies_in_canvas = function()
- [x] renderer.draw = function()
- [x] renderer.draw_loop = function()
- [x] 99_start.js
- [x] modules
- [ ] main.js
